{
    "score": "77",
    "comments": "====================\nTests for Part 1:\ntest_case01 (workspace.testing_suite_full.PartATestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 646, in test_case01\n    self.run_with_params(1, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case03 (workspace.testing_suite_full.PartATestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 652, in test_case03\n    self.run_with_params(3, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case05 (workspace.testing_suite_full.PartATestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 658, in test_case05\n    self.run_with_params(5, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\nSuccesses: 7\nFailures: 3\n\n====================\nTests for Part 2:\ntest_case01 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 699, in test_case01\n    self.run_with_params(1, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case04 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 708, in test_case04\n    self.run_with_params(4, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case05 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 711, in test_case05\n    self.run_with_params(5, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case06 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 714, in test_case06\n    self.run_with_params(6, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case07 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 717, in test_case07\n    self.run_with_params(7, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\ntest_case09 (workspace.testing_suite_full.PartBTestCase) Traceback (most recent call last):\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 723, in test_case09\n    self.run_with_params(9, self.params, self.test_method, self.student_method)\n  File \"/home/grader/marsglider/workspace/testing_suite_full.py\", line 616, in run_with_params\n    self.assertFalse(error_message, error_message)\nAssertionError: Test aborted due to timeout. Test was expected to finish in fewer than 10 second(s).\n\nSuccesses: 4\nFailures: 6\n\n====================\nOverall Score: 77\n"
}